// Copyright (C) 2012-2017 Hideaki Narita


#ifndef HNRT_XENSERVER_CONSTANTS_H
#define HNRT_XENSERVER_CONSTANTS_H


#define REFPREFIX "OpaqueRef:"
#define REFPREFIX_LENGTH 10
#define NULLREF reinterpret_cast<void*>(const_cast<char*>("OpaqueRef:NULL"))


#define ERROR_SESSION_INVALID "SESSION_INVALID"
#define ERROR_TRANSPORT_FAULT "TRANSPORT_FAULT"
#define ERROR_SESSION_AUTHENTICATION_FAILED "SESSION_AUTHENTICATION_FAILED"
#define ERROR_SR_BACKEND_FAILURE "SR_BACKEND_FAILURE"
#define ERROR_SERVER_FAULT "SERVER_FAULT"
#define ERROR_VM_SNAPSHOT_WITH_QUIESCE_NOT_SUPPORTED "VM_SNAPSHOT_WITH_QUIESCE_NOT_SUPPORTED"


#endif //!HNRT_XENSERVER_CONSTANTS_H
